### ISSUE TITLE
function name contains "."

### ISSUE THREAD

**Issue by wumo** [Glavo/gjavah#1]
Generated function name contains "." like 
```
JNIEXPORT jboolean JNICALL Java_org.test.HelloWorldJNI_sayhello
  (JNIEnv *, jobject);
```

**Comment by optyfr** [comment]
I confirm...
furthermore it is not backward compatible with original javah arguments (-jni is missing for example)

**Comment by Glavo** [comment]
I'm sorry that I neglected this project for a long time. This bug seems to have been fixed, but I'm sorry I didn't successfully release the new version. I will refocus on the project and fix any remaining problems.

**Comment by Glavo** [comment]
A new version 0.3.1 has been released, which should solve your problem.

Use it:
```groovy
repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.glavo.glavo:gjavah:0.3.1'
}
```
